name: flutter_frontend
description: Build together flutter frontend

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 18.0.0+18

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^0.13.3

  cached_network_image: ^3.1.0
  like_button: ^2.0.3
  persistent_bottom_nav_bar: ^4.0.2
  flutter_typeahead: ^3.2.1
  fluttertoast: ^8.0.8
  flutter_phoenix: ^1.0.0
  sqflite: ^2.0.0+4
  path: ^1.8.0
  image_picker: ^0.8.1
  pull_to_refresh: ^2.0.0
  numberpicker: ^2.1.1
  country_codes: ^2.1.1
  flutter_inapp_purchase: ^5.0.3
  polls: ^1.0.1
  profanity_filter: ^2.0.0

  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.9.2
  country_icons: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/launcher_icon.png"

flutter:

  uses-material-design: true

  assets:
    - assets/images/main_cover.jpg
    - assets/images/add_image.png
